app:
  config:
    baseUrl: "https://api.openweathermap.org/data/2.5/weather"
    apiKey: ${OPENWEATHER_API_KEY}
    unit: "metric"

spring:
  main:
    banner-mode: "off"
  ai:
    mcp:
      server:
        protocol: streamable
        name: "open-weather-mcp-server"

logging:
  level:
    root: INFO
    org:
      openweather: TRACE
  pattern:
    console:
